'''
This function was generated by ChatGPT
'''
def roman_to_int(s: str) -> int:
    # Define a dictionary of Roman numeral values
    roman_dict = {'I': 1, 'V': 5, 'X': 10, 'L': 50, 'C': 100, 'D': 500, 'M': 1000}

    # Initialize the output variable
    num = 0

    # Loop through the characters in the input string
    for i in range(len(s)):
        if i == len(s) - 1 or roman_dict[s[i]] >= roman_dict[s[i+1]]:
            # If this is the last character or the current character has a
            # higher or equal value than the next character, add its value
            # to the output variable
            num += roman_dict[s[i]]
        else:
            # If the current character has a lower value than the next
            # character, subtract its value from the output variable
            num -= roman_dict[s[i]]
    return num
